
## get all the users
GET http://localhost:3030/users

### get userID

GET http://localhost:3030/user/1

###Create a new user

POST http://localhost:3030/user/create HTTP/1.1
Content-Type: application/json

{
 "name": "Jose Perez",
  "email": "jsanchez@uni.edu.py",
  "password": "123456",
  "confPassword": "123456",
  "role": "admin",
  "notification": "true"
}   

### Update a user
PUT  http://localhost:3030/user/update/ba3e99b5-ca11-4c80-a2f1-0674ea2c975e HTTP/1.1
Content-Type: application/json

{
  "name": "Jose Perez",
  "email": "codeark35@gmail.com",
  "password": "12345",
  "confPassword": "12345",
  "role": "admin"
}   



### Reset password
PUT http://localhost:3030/user/reset-password/ba3e99b5-ca11-4c80-a2f1-0674ea2c975e HTTP/1.1
Content-Type: application/json

{
  "password": 123,
  "confPassword": 123,
  
}



### DELETE
DELETE  http://localhost:3030/user/delete/1df6de62-ec55-43e5-9a7d-e405892c6fa5


### Login
POST http://localhost:3030/login HTTP/1.1 
Content-Type: application/json

{
"email": "codeark35@gmail.com", 
"password": "123456"
}



### user
GET http://localhost:3030/me

###
DELETE http://localhost:3030/logout



###
POST http://localhost:3030/request/create HTTP/1.1
Content-Type: application/json

{
  "solicitud": "backend",

}
### get all the users
GET  http://localhost:3030/requests

### prueba
POST http://localhost:3030/send_recovery_email HTTP/1.1
Content-Type: application/json

{
  "recipient_email": "codeark35@gmail.com"
  

}